//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVoucherDTL
    {
        public Nullable<int> intVNo { get; set; }
        public int intId { get; set; }
        public Nullable<int> intCategory { get; set; }
        public Nullable<int> intItemCode { get; set; }
        public Nullable<int> intPieces { get; set; }
        public Nullable<double> floatRate { get; set; }
        public Nullable<double> floatCommission { get; set; }
        public Nullable<double> floatAmount { get; set; }
    }
}
