//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVoucher
    {
        public int intVoucherNo { get; set; }
        public Nullable<System.DateTime> dtDate { get; set; }
        public Nullable<int> intZoneName { get; set; }
        public Nullable<int> intSOName { get; set; }
    }
}
